/**
 * 오라클 View 관련 쿼리들을 정리
 */


-- VIEW 목록 조회
SELECT * FROM DBA_VIEWS;

SELECT * FROM ALL_ALL_TABLES;


INSERT INTO 
	( SELECT * FROM SCOTT.EMP e
		INNER JOIN SCOTT.DEPT d ON e.DEPTNO = d.DEPTNO 
		)
VALUES (9999,'KIM','CLERK',7566,SYSDATE,2900,NULL,20,20,'RESEARCH','DALLAS')
;

SELECT * FROM SCOTT.EMP e
		INNER JOIN SCOTT.DEPT d ON e.DEPTNO = d.DEPTNO;
	
-- MView Refresh 정책 확인

-- MView Refresh 정책 설정
EXEC DBMS_MVIEW.REFRESH('"SCOTT"."TEST_MV"','C');