/*DDL
데이터 베이스 내의 객체 을 생성/삭제/변경 하는 언어

객체란?
주로 테이블을 의미

DDL이 DML과 비견되는 가장 큰 특징
1. DML은 데이터 자체를 조작하지만, DDL은 데이터가 담기는 객체를 조작한다
2. DML은 TCL을 통해 변경이 확정되지만, DDL은 실행과 동시에 AUTO COMMIT된다
(왜 오토커밋인가? 
*/

-- CREATE 문
-- CREATE TABLE 테이블 이름 ( 열이름 열자료형, 열이름 열자료형, ...)
-- 열이름 규칙 : 
CREATE TABLE EMP_DDL (
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2), -- 전체 7자리, 소수점 2자리
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2));

DESC EMP_DDL;

-- CREATE AS문
-- CREATE TABLE 테이블명 AS 서브쿼리
CREATE TABLE DEPT_DDL
    AS SELECT * FROM DEPT;
    
DESC DEPT_DDL;

CREATE TABLE EMP_DDL_30
AS SELECT *
    FROM EMP
    WHERE DEPTNO=30;
    
SELECT * FROM EMP_DDL_30;

-- ALTER문
CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;
    
SELECT * FROM EMP_ALTER;

-- ADD 절
-- 테이블에 열을 추가하는 명령어
-- ALTER TABLE 테이블명 ADD (열이름 데이터타입, 열이름 데이터타입)
ALTER TABLE EMP_ALTER
ADD HP VARCHAR2(20);

ALTER TABLE EMP_ALTER
ADD (TEL VARCHAR2(20), AGE NUMBER(3));

-- RENAME절
-- 테이블 열 이름을 변경하는 명령어
-- ALTER TABLE 테이블명 RENAME COLUMN 열이름 TO 열이름
 
-- MODIFY절
-- 테이블 열 데이터타입을 변경하는 명령어
-- ALTER TABLE 테이블명 MODIFY 열이름 데이터타입
-- (기존에 저장된 데이터와 다른 데이터타입으로는 변경 불가)
ALTER TABLE EMP_ALTER
MODIFY HP NUMBER(10);

ALTER TABLE EMP_ALTER
MODIFY SAL NUMBER(10,2); -- 실행 가능

DESC EMP_ALTER;

ALTER TABLE EMP_ALTER
MODIFY SAL NUMBER(1); -- 에러 발생!

ALTER TABLE EMP_ALTER
MODIFY ENAME NUMBER(10); -- 에러 발생!

-- RENAME 문
-- 테이블의 이름을 바꾸는 명령어
-- RENAME 테이블명 TO 테이블명
RENAME EMP_ALTER TO EMP_RENAME;

SELECT * FROM EMP_ALTER;

SELECT * FROM EMP_RENAME;

-- TRUNCATE 문
-- 테이블에 저장된 데이터를 모두 지우는 명령어
TRUNCATE TABLE EMP_RENAME;

SELECT * FROM EMP_RENAME;

ROLLBACK; -- DDL은 Auto Commit이므로 롤백해도 소용 없음

-- DROP 문
-- 테이블 자체를 지우는 명령어
DROP TABLE EMP_RENAME;

--Q1
CREATE TABLE EMP_HW (
    EMPNO NUMBER(4)
    ,ENAME VARCHAR2(10)
    ,JOB VARCHAR2(9)
    ,MGR NUMBER(4)
    ,HIREDATE DATE
    ,SAL NUMBER(7,2)
    ,COMM NUMBER(7,2)
    ,DEPTNO NUMBER(2)
    );

DESC EMP_HW;

--Q2
ALTER TABLE EMP_HW
ADD BIGO VARCHAR2(20);

--Q3
ALTER TABLE EMP_HW
MODIFY BIGO VARCHAR2(30);

--Q4
ALTER TABLE EMP_HW
RENAME COLUMN BIGO TO REMARK;

--Q5

-- Q6
DROP TABLE EMP_HW;