-- 제목 : 입양 시각 구하기(1)
SELECT TO_CHAR(DATETIME,'HH24') AS HOUR,
    COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME,'HH24')
HAVING TO_CHAR(DATETIME,'HH24') >= 9 AND TO_CHAR(DATETIME,'HH24') < 20
ORDER BY HOUR

