-- 제목 : 보호소에서 중성화한 동물
SELECT O.ANIMAL_ID,O.ANIMAL_TYPE,O.NAME
FROM ANIMAL_OUTS O
INNER JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE 
    (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')
    AND I.SEX_UPON_INTAKE LIKE 'Intact%'