/**
 * CMS 데이터 분석용 쿼리
 */
-- 외부테이블 생성
CREATE DATABASE IF NOT EXISTS medicare_part_b;

CREATE EXTERNAL TABLE IF NOT EXISTS medicare_part_b.medicare_part_b_2013_raw(
	NPI STRING,
	NPPES_PROVIDER_LAST_ORG_NAME STRING,
	NPPES_PROVIDER_FIRST_NAME STRING,
	NPPES_PROVIDER_MI STRING,
	NPPES_CREDENTIALS STRING,
	NPPES_PROVIDER_GENDER STRING,
	NPPES_ENTITY_CODE STRING,
	NPPES_PROVIDER_STREET1 STRING,
	NPPES_PROVIDER_STREET2 STRING,
	NPPES_PROVIDER_CITY STRING,
	NPPES_PROVIDER_ZIP STRING,
	NPPES_PROVIDER_STATE STRING,
	NPPES_PROVIDER_COUNTRY STRING,
	PROVIDER_TYPE STRING,
	MEDICARE_PARTICIPATION_INDICATOR STRING,
	PLACE_OF_SERVICE STRING,
	HCPCS_CODE STRING,
	HCPCS_DESCRIPTION STRING,
	HCPCS_DRUG_INDICATOR STRING,
	LINE_SRVC_CNT INT,
	BENE_UNIQUE_CNT INT,
	BENE_DAY_SRVC_CNT INT,
	AVERAGE_MEDICARE_ALLOWED_AMT DOUBLE,
	STDEV_MEDICARE_ALLOWED_AMT DOUBLE,
	AVERAGE_SUBMITTED_CHRG_AMT DOUBLE,
	STDEV_SUBMITTED_CHRG_AMT DOUBLE,
	AVERAGE_MEDICARE_PAYMENT_AMT DOUBLE,
	STDEV_MEDICARE_PAYMENT_AMT DOUBLE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE
LOCATION '/user/root/medicare_raw'
TBLPROPERTIES ("skip.header.line.count"="2");

SELECT * FROM medicare_part_b.medicare_part_b_2013_raw LIMIT 10;